spring:
  application:
    name: books-api

  #  volatile in-memory database
  datasource:
    url: jdbc:h2:mem:bookdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect